# Generated by Django 4.2.4 on 2023-08-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0002_plant_usernotification_userfavoriteplants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='atmospheric_humidity',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='foliage_color',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='foliage_texture',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='fruit_color',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='fruit_conspicuous',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='growth_form',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='growth_habit',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='growth_rate',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='leaf_retention',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='light',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='shape_and_orientation',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='soil_nutriments',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='soil_salinity',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='soil_texture',
        ),
    ]
