# Generated by Django 4.2.4 on 2023-08-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0003_remove_plant_atmospheric_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
