# Generated by Django 4.2.4 on 2023-08-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0004_communitypost_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
