# Generated by Django 4.2.4 on 2023-08-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0005_alter_communitypost_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='vegetable',
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
