# Generated by Django 4.2.4 on 2023-08-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0006_remove_plant_vegetable_alter_communitypost_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_posts/'),
        ),
    ]
