# Generated by Django 4.2.4 on 2023-08-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0008_plant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
