# Generated by Django 4.2.4 on 2023-08-25 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0009_alter_plant_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
