# Generated by Django 4.2.4 on 2023-08-25 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0013_remove_communitypost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='postId',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
