# Generated by Django 4.2.4 on 2023-08-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0014_communitypost_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
