# Generated by Django 4.2.4 on 2023-08-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0015_communitypost_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='poster',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
