# Generated by Django 4.2.4 on 2023-08-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0016_communitypost_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='poster',
        ),
    ]
