# Generated by Django 4.2.4 on 2023-08-26 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0017_remove_communitypost_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoriteplants',
            name='plant_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfavoriteplants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hb.user'),
        ),
    ]
