# Generated by Django 4.2.4 on 2023-08-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0020_userpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavoriteplants',
            name='plant_name',
        ),
    ]
