# Generated by Django 4.2.4 on 2023-08-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0021_remove_userfavoriteplants_plant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoriteplants',
            name='plant_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
