# Generated by Django 4.2.4 on 2023-08-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0023_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
